<a href="https://colab.research.google.com/github/mamatqobulovsardor/data/blob/main/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
!wget https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks/data/births.csv

--2024-12-21 15:08:39--  https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks/data/births.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 264648 (258K) [text/plain]
Saving to: ‘births.csv’

births.csv          100%[===================>] 258.45K  --.-KB/s    in 0.04s

2024-12-21 15:08:39 (7.09 MB/s) - ‘births.csv’ saved [264648/264648]

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/refs/heads/master/notebooks/data/births.csv')
df

       year  month  day gender  births
0      1969      1  1.0      F    4046
1      1969      1  1.0      M    4440
2      1969      1  2.0      F    4454
3      1969      1  2.0      M    4548
4      1969      1  3.0      F    4548
...     ...    ...  ...    ...     ...
15542  2008     10  NaN      M  183219
15543  2008     11  NaN      F  158939
15544  2008     11  NaN      M  165468
15545  2008     12  NaN      F  173215
15546  2008     12  NaN      M  181235

[15547 rows x 5 columns]

In [4]:
df.isnull().sum()

year        0
month       0
day       480
gender      0
births      0
dtype: int64

In [5]:
df['day'] = df['day'].fillna(df['day'].mean())

In [6]:
df

       year  month        day gender  births
0      1969      1   1.000000      F    4046
1      1969      1   1.000000      M    4440
2      1969      1   2.000000      F    4454
3      1969      1   2.000000      M    4548
4      1969      1   3.000000      F    4548
...     ...    ...        ...    ...     ...
15542  2008     10  17.769894      M  183219
15543  2008     11  17.769894      F  158939
15544  2008     11  17.769894      M  165468
15545  2008     12  17.769894      F  173215
15546  2008     12  17.769894      M  181235

[15547 rows x 5 columns]

In [8]:
df.isnull().sum()

year      0
month     0
day       0
gender    0
births    0
dtype: int64